import Head from "next/head"
import type { InferGetStaticPropsType } from "next/types"
import Carousel from "../components/carousel/carousel"
import Quote from "../components/quote/quote"
import { PATH } from "../constants/constants"
import { getPaintings } from "../services/painting"

export default function Home({ paintings }: InferGetStaticPropsType<typeof getStaticProps>) {
  const carouselItems = paintings.map(painting => ({
    id: painting.id,
    title: painting.title,
    imageUrl: `${PATH.PAINTINGS.SOURCE}/${painting.filename}`,
    imageWidth: painting.imageWidth,
    imageHeight: painting.imageHeight,
  }))

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel items={carouselItems} />

      <section>
        <Quote>
          <p>
            Dans des huiles posées avec précision sur un décor soigné, support en bois ou portail en
            biseau, il décline des ostéomorphes placés plus souvent verticalement sur fond uni noir
            de préférence, fichés sur un tube d&apos;acier ou articulés les uns aux autres, formant
            un monde sculptural étrange.
          </p>
          <p>
            De temps à autre une allusion au vivant comme cette construction dans laquelle se
            détache un bec d&apos;oiseau.
          </p>
          <p>
            Si Hellée, (1999) représente cette peinture dans laquelle la sculpture est implicite, il
            annonce une explicite sculpture de bois, peint, Hellée, (2009).
          </p>
          <p>
            Un portique laisse pendre, ossement acérés, des cadres et des boules dans une allégorie
            létale de tarlatane colorée. 2007
          </p>
          <cite className="mt-10 block">
            <p className="text-end">Le Delarge</p>
          </cite>
        </Quote>
      </section>
    </>
  )
}

export const getStaticProps = async () => {
  const paintings = getPaintings().slice(0, 5)
  return {
    props: {
      paintings,
    },
  }
}
